# Configuraci√≥n de Correo
send_mail: true
smtp_host: "smtp.gmail.com"

# Reporte
report_dir: "/tmp/ocp-reports"
report_file: "reporte-seguridad-{{ lookup('pipe', 'date +%Y%m%d') }}"
date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"


#Namespaces filtrados en network policies
system_ns_regex: "^(openshift.*|kube.*|default|stackrox)$"
