---
# Defaults del rol compliance_export_html

# CAMBIO: Usamos un nombre nuevo para evitar conflictos con variables externas recursivas
compliance_reports_path: "/tmp/compliance-reports"

compliance_report_html_name: "compliance-report.html"
# email_to viene del exterior

