---
version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:latest

dependencies:
  galaxy: requirements.yml
  system: bindep.txt
  # --- SECCIÃ“N NUEVA: Requerida para evitar el error de check_ansible ---
  ansible_core:
    package_pip: ansible-core>=2.15
  ansible_runner:
    package_pip: ansible-runner>=2.3
  # ---------------------------------------------------------------------

additional_build_steps:
  prepend_base:
    - RUN pip install --upgrade pip setuptools
  
  append_final:
    - RUN echo "Verificando binarios..." && oscap --version && ansible --version
