---
# Defaults del rol toggle_policies

# Ruta temporal
gitops_repo_path: "/tmp/acm-policies"

# Etiquetas
placement_label_key: "compliance"
placement_label_value: "enabled"

# Definici√≥n de estado (Booleano puro)
cis_disabled: false
pci_disabled: true

